Sources/MySQL/Bind+Value.swift
Rely on field length instead of null terminator for String conversion.
Should fix #10
=> concurrency fix

README.md
Heroku fails build Vapor app with MySQL, we need to set the buildpack to `https://github.com/loganwright/heroku-buildpack-swift`
Updated the readme with heroku instructions.
=> updated readme with heroku instructions

Sources/MySQL/Connection.swift, Sources/MySQL/Database.swift
Note: You will still need to manually alter tables to support this encoding. See vapor/fluent#74.
=> Custom encoding support

README.md
The new section is basically a copy of the original "building" section. Only paths have changed. Also macports have versioned ports for different mysql versions. So it's probably a good idea to either abstract it away in a readme.
=> Add instructions for macports

Sources/MySQL/Connection.swift
The result type of strlen changes with word size, but
mysql_stmt_prepare's third argument is fixed as an unsigned long.  This
explicitly coerces the type to match.  On 64-bit it's optimized away.
=> Type coersion for 32-bit platforms

Sources/MySQL/Connection.swift
From [the documentation](http://dev.mysql.com/doc/refman/5.7/en/option-files.html): "Most MySQL programs can read startup options from option files (sometimes called configuration files). Option files provide a convenient way to specify commonly used options so that they need not be entered on the command line each time you run a program."
A simple change allows Vapor to read these files as well.
By default, Vapor will read the contents of the `[client]` group (which all client programs do) as well as the `[vapor]` group. Passing in an `optionsGroupName` to `init()` will cause it to read from that group instead of `[vapor]`.
=> Vapor to respect option files like my.cnf

Sources/MySQL/Database.swift
Opening up the encoding constant should offer a bit more flexibility in the `mysql-driver` to fix e.g. this TODO: https://github.com/vapor/mysql-driver/blob/master/Sources/FluentMySQL/MySQLSerializer.swift#L17
=> Open up encoding constant

Sources/MySQL/Connection.swift, Tests/LinuxMain.swift, Tests/MySQLTests/MySQLTests.swift
Added basic support for transactions. If one of the embedded calls fails the transaction will be rolled back and the error will be re-thrown. On success, the transaction will be committed.
```swift
try connection.transaction {
try connection.execute(...)
}
```
=> Added Transaction to connection

Sources/MySQL/Field.swift
The Field.name getter is being called for every row fetched from the
database. Having it as a computed property is unnecessary overhead,
considering that the result set metadata may not change.
Turning it into precalculated property decreases query execution time
by ~40%.
=> Convert field names only once per query

Sources/MySQL/Connection.swift
Xcode's time profiler shows that a distinguishable amount of time is
wasted by allocating/deallocating memory for every row.
Reusing the same dictionary reduces query time by 5% in my tests. The
change is trivial and safe, because all the values will be overwritten
by the for loop.
=> Reuse the parsed dictionary during a query to reduce allocations

Sources/MySQL/Bind/Bind.swift, Sources/MySQL/Bind/Binds.swift, Sources/MySQL/Connection.swift
This changes the MySQL result buffer to only allocate enough memory to hold the largest actual result, instead of allocating enough memory to hold the largest _theoretical_ result.
This should prevent issues with using `LONGTEXT` columns on machines with limited RAM. (Unless of course there is actually a huge amount of data stored in one of these columns).
Result buffers (binds) are now created _after_ the results have been stored client side (in the libraries internal buffers). This important re-ordering of events is what allows us to create our result buffers after the `max_length` is known.
=> use `field.max_length` instead of `field.length`

Package.swift, Sources/MySQL/Connection/Connection.swift, Sources/MySQL/Connection/PacketParser.swift, Sources/MySQL/Internals/Handshake.swift, Sources/MySQL/Internals/MySQLStream.swift, Sources/MySQL/Internals/Packet.swift, circle.yml
Hi,
1. The outgoing packet sequenceId was broken, it got optimized out  from the source, so when it allocates packet the sequenceid field (4. byte of the buffer) contains random data. This PR fix this and set it to zero. I don't touch the handshake sequenceid generation where it is used (yet). 
Later on the packet fragmentation needs to be adressed thought because the servers are using this even when it  has no practical usage. 
2. The incoming packet length was incorrectly calculated, therefore all packets bigger than 255 byte likely causing memory errors
3. fixing dependencies to beta.1 tag
=> Fixing packet sequenceId bug and incorrect incoming packet lengh calculations

Sources/MySQL/Internals/Handshake.swift, Sources/MySQL/Internals/Task.swift, Sources/MySQL/Query/Connection+Query.swift, Tests/MySQLTests/MySQLTests.swift, circle.yml
The driver several times improperly implementing the MySQL Client-Server protocol
Generally the ERR_Packet parsing is what missed.
If the server sending an ERR_Packet it was misinterpreted or not interpreted at all
Misinterpretation was in connection handshake task, when the server sent a ERR_packet
with `Too many connections` error, it was interpreted as handshake error and misleading the
developer
Silencing an error much more dangerous.
For example the PrepareQuery task can hang the server thread if sends to the server a
wrong SQL query.
The server will respond with an ERR_Packet which was simply ignored.
This method have a closure which must be called with a preprared statement for binding
The error condition must be delivered to this closure to be able to fail the promise
Other places …
=> Fix some error processing bugs in driver, please read the commit message and follow!

Sources/MySQL/Parsing/Row+Parsing.swift, Sources/MySQL/Parsing/RowDecoder.swift
Why:
MySQL types .bit and .timstamp were not supported
How:
Added case in the parser for .bit by assuming length was never > 1 byte
Added case in the parser for .timestamp using the same parser as .date
=> Add support for .bit & .timestamp, add decode case for .string

Sources/MySQL/Connection/PacketParser.swift, Sources/MySQL/Parsing/ParsingHelpers.swift, Sources/MySQL/Parsing/Row+Parsing.swift, Sources/MySQL/Query/Binding+Encoder.swift, Tests/MySQLTests/MySQLTests.swift
=> null column support

Sources/MySQL/Database/MySQLDatabaseConfig.swift
Simplifies setting up a config
=> Default port in MySQLDatabaseConfig to 3306

Sources/MySQL/Connection/MySQLConnection+Authenticate.swift
`SHA1.digest` is renamed to `hash`.
Followed change to eliminate warnings.
=> Follow API change in Crypto

Sources/MySQL/Connection/MySQLData.swift
Add initializer to MySQLData for Decimal values and a MySQLDataConvertible extension on Decimal so it can be converted from and to string-form as expected by MYSQL_TYPE_{,NEW}DECIMAL.
=> Add support for loading and storing Decimal

Sources/MySQL/Connection/MySQLConnection+Authenticate.swift, Sources/MySQL/Database/MySQLDatabase.swift, Sources/MySQL/Database/MySQLDatabaseConfig.swift, Sources/MySQL/Database/MySQLProvider.swift, Sources/MySQL/Protocol/MySQLCharacterSet.swift, Tests/MySQLTests/MySQLPacketTests.swift, Tests/MySQLTests/MySQLTests.swift
MySQL’s utf8 charset only partially implements proper UTF-8 encoding. It can only store UTF-8-encoded symbols that consist of one to three bytes; encoded symbols that take up four bytes aren’t supported.
Luckily, MySQL 5.5.3 (released in early 2010) https://dev.mysql.com/doc/relnotes/mysql/5.5/en/news-5-5-3.html introduced a new encoding called utf8mb4 which maps to proper UTF-8 and thus fully supports Unicode.
10.9.1 The utf8mb4 Character Set (4-Byte UTF-8 Unicode Encoding) https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-utf8mb4.html
=> Support for Emoticons Unicode

Sources/MySQL/Connection/MySQLConnection+Authenticate.swift, Sources/MySQL/Database/MySQLDatabase.swift, Sources/MySQL/Database/MySQLDatabaseConfig.swift, Sources/MySQL/Pipeline/MySQLPacketDecoder.swift, Sources/MySQL/Protocol/MySQLCapabilities.swift, Sources/MySQL/Protocol/MySQLEOFPacket.swift, Sources/MySQL/Protocol/MySQLErrorPacket.swift, Sources/MySQL/Protocol/MySQLHandshakeResponse41.swift, Sources/MySQL/Protocol/MySQLHandshakeV10.swift, Sources/MySQL/Protocol/MySQLOKPacket.swift, Tests/MySQLTests/MySQLPacketTests.swift
Took over from #163.
This PR contains 3 changes.
1. Change `MySQLCapabilities` and `MySQLCapability` into `MySQLCapabilities: OptionSet`
2. Make `MySQLCapabilities` public
3. Add `capabilities` in `MySQLDatabaseConfig`
All capability flags are turned into static member of `MySQLCapabilities`. 
There is also `MySQLCapabilities.default` which is took from [here](https://github.com/vapor/mysql/blob/cda473257572c8e02706d0c65fd145765c5a414d/Sources/MySQL/Connection/MySQLConnection%2BAuthenticate.swift#L50-L54).
Threre was [DIctionary literal initializer](https://github.com/vapor/mysql/blob/cda473257572c8e02706d0c65fd145765c5a414d/Sources/MySQL/Protocol/MySQLCapabilities.swift#L35-L44) but I didn't take over this because it looks unnecessary.
=> Changes around `MySQLCapabilities`

Sources/MySQL/Protocol/MySQLCapabilities.swift, Sources/MySQL/Protocol/MySQLHandshakeResponse41.swift, Sources/MySQL/Protocol/MySQLHandshakeV10.swift
Circumvented an assert in MySQLHandshakeV10.swift that failed with MariaDB 10.2 or later because of specific flags.
See: [MariaDB Initial Handshake Packet specific flags](https://mariadb.com/kb/en/library/1-connecting-connecting/)
=> Extended MySQLCapabilities with MariaDB specific capabilities

Sources/MySQL/Connection/MySQLConnection+Query.swift, Sources/MySQL/Connection/MySQLConnection.swift, Sources/MySQL/Connection/MySQLConnectionHandler.swift, Sources/MySQL/Pipeline/MySQLPacketDecoder.swift, Sources/MySQL/Pipeline/MySQLPacketEncoder.swift, Tests/MySQLTests/MySQLTests.swift, circle.yml, docker-compose.yml
Moving from `QueueHandler` to a specialized `MySQLConnectionHandler` created some issues with the old `CLIENT_DEPRECATED_EOF` support. This update fixes the `MySQLPacketEncoder` to parse deprecated EOF packets _before_ firing inbound packet events to avoid state being overwritten.
=> fix deprecated EOF support for MySQL 5.5 and 5.6

Sources/MySQL/Connection/MySQLData.swift, Sources/MySQL/Data/MySQLData+Decimal.swift, Sources/MySQL/SQL/MySQLDataType.swift, Sources/MySQL/SQL/MySQLDataTypeStaticRepresentable.swift, Tests/MySQLTests/MySQLTests.swift
This PR proposes changing the storage method of `Decimal` implemented by #171. The problem with the previous implementation is that `Foundation.Decimal` can represent much larger values than MySQL's `DECIMAL` is able to store. Foundation's `Decimal` type includes a `Codable` implementation that losslessly stores the data. This PR simply removes the custom `MySQLDataConvertible` implementation so that `Decimal` falls back on its default `Codable` encoding.
The downside to this change is that it will be harder to work with `Decimal` values directly in MySQL. The upside is that any `Decimal` value you can represent in Swift can be losslessly stored in your data layer.
This PR is up for discussion!
=> store Decimal using Codable impl

Sources/MySQL/Codable/MySQLRowDecoder.swift, Sources/MySQL/Connection/MySQLColumn.swift
Adds a couple of changes to the MySQL row decoder to improve its performance. `allKeys` is no longer computed or used. This check was redundant since `decodeNil` does the same thing. The `firstRow` code was also improved to take better advantage of existing dictionary lookup algorithms. 
Addresses #206.
=> improve MySQL row decoder performance

Sources/MySQL/Codable/MySQLDataEncoder.swift, Tests/MySQLTests/MySQLTests.swift
Fixes an issue where directly encoding zero length arrays would result in a nil force unwrap.
Fixes #221.
=> add support for encoding zero-length arrays

Sources/MySQL/Connection/MySQLData.swift, Tests/MySQLTests/MySQLTests.swift
Adds `CustomStringConvertible` conformance to `MySQLTime`. Fixes #218.
=> add MySQLTime description

Sources/MySQL/Connection/MySQLConnection.swift
This fixes retain cycle in the case of a callback enum:
self -> handler.state -> self (in block)
I do not know whether this is related to issue https://github.com/vapor/mysql/issues/203, but it may...
=> Fixed memory leak

Sources/MySQL/Utilities/ByteBuffer+MySQL.swift
This PR fixes an unnecessary byte buffer copy that was triggered by using `set()` in a function for reading packet length. The set is not necessary since we can clear the upper bits more efficiently using `&`.
=> fix bytebuffer copy

Sources/MySQL/SQL/MySQLAlterTable.swift
Allow for constraints to be dropped in MySQL alter table. 
Fixes https://github.com/vapor/fluent-mysql-driver/issues/148
=> alter delete constraint

Sources/MySQLKit/MySQLDatabase.swift
Setting pass a nil TLSConfiguration specifically means "don't use TLS" which we no longer want to be the default behavior. Passing a TLSConfiguration signals the client to use TLS if the server supports it.
=> fix tls configuration defaults

Sources/MySQLKit/MySQLDatabase.swift, Tests/MySQLKitTests/MySQLKitTests.swift
Fixes a bug causing columns with null values to not correctly decode to Swift optionals (fixes #255, #256).
=> Correctly decode null columns

Sources/MySQLKit/MySQLDatabase.swift
Adds `MySQLConfiguration(unixDomainSocketPath:)` initializer for connecting to MySQL over a unix socket (#263, https://github.com/vapor/fluent-mysql-driver/issues/161).
=> Add unix socket option to MySQLConfiguration

Sources/MySQLKit/MySQLDatabase.swift
Small fix to allow optional `database` string in new `MySQLConfiguration` for unix domain socket path (#264).
=> Allow optional database in MySQLConfiguration

Package.swift, Sources/MySQLKit/MySQLDatabase.swift, Tests/MySQLKitTests/MySQLKitTests.swift
Overrides `SQLDataType.text` to use `VARCHAR` instead of `TEXT` (#265).
=> Use VARCHAR instead of TEXT

Sources/MySQLKit/MySQLDataDecoder.swift
Replaces a force unwrap in `MySQLDataDecoder` with a Swift error (#274).
=> Fix decode force unwrap

Package.swift
Semver-major is more trouble than it's worth sometimes.
Need a new release to bump `Package.swift`. There's no change to MySQLKit's API whatsoever so it's semver-patch here.
=> Require the new semver-major RC of mysql-nio

Tests/MySQLKitTests/MySQLKitTests.swift
The unit tests now respect `MYSQL_USERNAME`, `MYSQL_PASSWORD`, `MYSQL_DATABASE`, and `MYSQL_PORT`. (`MYSQL_HOSTNAME` was already supported.)
No semver tag as updating the unit tests does not require a release.
=> Make unit tests respect env var overrides for DB connection

.github/workflows/test.yml, Package.swift, Sources/MySQLKit/MySQLConfiguration.swift, Sources/MySQLKit/MySQLDataDecoder.swift, Tests/MySQLKitTests/MySQLKitTests.swift
See commit log for details; in short, the `MySQLDataDecoder` logic has been retooled to fix some usage errors, address a couple of very minor bugs, and slightly improve performance. Additional changes:
- Fixes `TLSConfiguration.forClient()` deprecation warnings by using `.makeClientConfiguration()` instead as recommended.
- Some well-overdue updates to CI for this package.
Note: While these changes do not add any new public API, they are nonetheless marked as `semver-minor` to reflect the addition of a new explicit dependency on a recent version of NIOSSL.
=> Address issues in decoding data from the database

.github/workflows/test.yml, Package.swift, Sources/MySQLKit/MySQLDialect.swift, Tests/MySQLKitTests/MySQLKitTests.swift
Also enables correctly running the expanded SQLKit benchmark suite.
semver-minor because the new SQLKit version requirement is a semver-minor bump.
=> Enable UPSERT support for MySQL

Tests/MySQLKitTests/MySQLKitTests.swift
We shouldn't be resetting databases arbitrarily this way anyway, and removing it fixes a "doesn't honor the MYSQL_DATABASE env var" bug.
=> Don't drop an arbitrarily specified database when tests are run

Package.swift, Sources/MySQLKit/MySQLDialect.swift
Leverages the new dialect flags from [vapor/sql-kit#144](https://github.com/vapor/sql-kit#144) to enable full `UNION` queries according to MySQL's support.
The increased SQLKit version requirement makes this a `semver-minor` change.
=> Declare supported UNION features

Package.swift
This solves users of Fluent's MySQL driver getting silently stuck on version 1.1.6 of `swift-crypto` (the current, source-compatible version is 2.0.3).
It would be far preferable to replace the usage of `Insecure.SHA1` in `MySQLDialect` with something better suited to the purpose and thus drop the Crypto dependency in MySQLKit altogether, but we can't do that without breaking migrations in existing databases.
Due to the change in dependency version requirement, this is `semver-minor`.
=> Fix SwiftCrypto version pin

Sources/MySQLKit/MySQLConfiguration.swift
Addresses issue: https://github.com/vapor/fluent-mysql-driver/issues/211
This allows the `MySQLConfiguration` to be edited after it has been instantiated, for example setting a `TLSConfiguration`
=> Allow `MySQLConfiguration` to be updated

Sources/MySQLKit/MySQLDialect.swift
Leverages the new functionality in vapor/sql-kit#154 to provide the correct syntax for both shared and exclusive locking clauses in MySQL.
=> Add locking clause syntax to dialect

Sources/MySQLKit/MySQLDataEncoder.swift, Tests/MySQLKitTests/MySQLKitTests.swift
This avoids possible incorrect/corrupted output for various legal Encodable uses.
=> Revise MySQLDataEncoder implementation to better handle various Codable conformances

.github/workflows/test.yml, Package.swift, Sources/MySQLKit/MySQLDialect.swift, Tests/MySQLKitTests/MySQLKitTests.swift
Also includes:
- Another round of CI improvements
- A huge speed boost for `MySQLDialect.normalizeSQLConstraint(identifier:)` (converting the hash result to hexadecimal no longer relies on the use of printf formatting)
=> Drop support for Swift 5.4

Sources/MySQLKit/MySQLDialect.swift
#314 included a new routine for hex-formatting the hash used for constraint name normalization. This PR fixes a bug in that routine which caused the 4th bit of every byte to be ignored when formatting.
=> Fix bug in hex encoding of normalized constraint hashes

.github/workflows/test.yml, Sources/MySQLKit/MySQLConfiguration.swift, Sources/MySQLKit/MySQLConnectionSource.swift
Prior to this, hostname in `MySQLConnection.connect()` was optional and defaulted to nil. This resulted in an error where upon entering url for connection string, apple's swift-nio-ssl threw: `NIOSSLExtraError.failedToValidateHostname: Couldn't find <none> in certificate from peer` By adding hostname from user given configuration, this is fixed.
Fixes #311
=> Add `hostname` to `MySQLConnection.connect()`

.api-breakage/allowlist-branch-nested-subpath-expressions.txt, .github/workflows/test.yml, Package.swift, Sources/MySQLKit/MySQLDialect.swift
Implements SQLKit's new `SQLDialect.nestedSubpathExpression(in:for:)` method.
=> Add MySQL support for nested subpath (JSON) expressions

Package.swift
Bump swift-crypto version range to `1.0.0 ..< 4.0.0` since the current version is 3.1.0.
=> Bump swift-crypto version range

Package.swift, Package@swift-5.9.swift, Sources/MySQLKit/MySQLDatabase+SQL.swift
Now supports query logging with the same semantics as the other drivers. When a query is executed with query logging enabled at or above the logger's current log level, the actual SQL query and its accompanying array of bound parameters (if any) are logged as structured metadata on the logger using a generic message. This follows the [recommended guidelines for logging in libraries](https://www.swift.org/documentation/server/guides/libraries/log-levels.html). Credit goes to @MahdiBM for the original suggestion.
Before:
```
2024-05-29T00:00:00Z debug codes.vapor.fluent : database-id=mysql [MySQLKit] SELECT * FROM foo WHERE a=? [["bar"]]
```
After:
```
2024-05-29T00:00:00Z debug codes.vapor.fluent : database-id=mysql sql=SELECT * FROM foo WHERE a=? binds=["bar"] [MySQLKit] Executing query …
```
=> Actually support query logging
