Tests/MySQL/MySQLTests.swift

Adds a single test, mainly using this to run Travis for some stuff that was merged into master.

double test

---

Sources/MySQL/Bind+Node.swift

Fixes an issue that occurs while reading TINYINT values from the buffer.
See #31

Fix TINYINT buffer issue

---

Sources/MySQL/Bind.swift
Sources/MySQL/Binds.swift
Sources/MySQL/Connection.swift
Sources/MySQL/Database.swift
Sources/MySQL/Error.swift
Sources/MySQL/Field.swift
Tests/MySQLTests/MySQLTests.swift
Tests/MySQLTests/Utilities.swift

Memory bug

---

Sources/MySQL/Bind+Node.swift

Add support for MySQL FLOAT fields mapping them to Double (Node.number.double)

Add support for MySQL FLOAT fields

---

Sources/MySQL/Bind+Node.swift
Tests/MySQLTests/MySQLTests.swift

From #83 
@vzsg take a look and let me know if this satisfies your issue proposal.

blob type to raw bytes

---

README.md
Sources/MySQL/Connection.swift
Tests/MySQLTests/MySQLTests.swift
circle.yml

Detects closed connections by catching an appropriate error. This is much more efficient than pinging.

connection

---

Sources/MySQL/Connection.swift
Tests/MySQLTests/MySQLTests.swift

To finish the loop - following  vapor/mysql-driver@e0c8529

Adds generic return value to transaction closure

---

Sources/MySQL/Bind/Bind.swift

specify more flexible timezone to avoid obscure crashes

---

Sources/MySQL/Bind/Bind.swift
Sources/MySQL/Connection.swift
Tests/MySQLTests/MySQLTests.swift

[Repro] Longtext columns cause crash on low memory systems

---

Package.swift

This PR is fixing dependencies to the rest of the vapor framework packages.

Fixing dependecies

---

Sources/MySQL/Parsing/RowDecoder.swift
Sources/MySQL/Query/Binding+Encoder.swift
Sources/MySQL/Query/Binding.swift
Tests/MySQLTests/MySQLTests.swift

bool fixes

---

Sources/MySQL/Connection/MySQLData.swift
Sources/MySQL/Pipeline/MySQLPacketDecoder.swift
Sources/MySQL/Protocol/MySQLBinaryResultsetRow.swift
Sources/MySQL/Protocol/MySQLDataType.swift

mysql json type

---

circle.yml

also test fluent-mysql integration

---

Sources/MySQL/Connection/MySQLData.swift

(I haven't tested this one yet, would like to do that via CI.)

Hopefully fix microsecond support in MySQL as well

---

Package.swift
Sources/MySQL/Connection/MySQLConnection+Authenticate.swift
Sources/MySQL/Connection/MySQLConnection.swift
Sources/MySQL/Connection/MySQLData.swift
Sources/MySQL/Database/MySQLDatabase.swift
Sources/MySQL/Database/MySQLLogger.swift
Sources/MySQL/Database/MySQLProvider.swift
Sources/MySQL/Pipeline/MySQLConnectionSession.swift
Sources/MySQL/Pipeline/MySQLPacketDecoder.swift
Sources/MySQL/Protocol/MySQLHandshakeV10.swift
Tests/MySQLTests/MySQLPacketTests.swift
Tests/MySQLTests/MySQLTests.swift
circle.yml

dbkit 1.0.0 gm

---

Sources/MySQL/SQL/MySQLAlterTable.swift
Tests/MySQLTests/MySQLTests.swift

add support for adding columns _after_ other columns

---

Sources/MySQL/Connection/MySQLData.swift

Creates a shared `DateComponents` struct for parsing `MySQLTime`. See http://jordansmith.io/performant-date-parsing/. This resulted in a >10x speedup for parsing a 100 count result set that contained multiple date fields.

shared DateComponents struct

---

Sources/MySQL/Connection/MySQLConnectionHandler.swift
Sources/MySQL/Pipeline/MySQLPacketDecoder.swift
Tests/MySQLTests/MySQLTests.swift

ignore packets after aborted query

---

Sources/MySQL/Connection/MySQLConnection+SimpleQuery.swift

log simple query

---

Sources/MySQL/Connection/MySQLData.swift
Tests/MySQLTests/MySQLTests.swift

Fixes https://github.com/vapor/mysql/issues/235

JSON Binary Data Type

---

Sources/MySQL/Connection/MySQLData.swift

Errors related to Float80 when trying to compile on Raspberry Pi 3.

Fixed Issue #215: Compatibility on ARM.

---

Sources/MySQLKit/MySQLDataDecoder.swift

Decode JSON array in MySQLDataDecoder

---

Sources/MySQLKit/MySQLDataDecoder.swift
Sources/MySQLKit/MySQLDataEncoder.swift

Add support for encoding/decoding arrays.

add array coding support

---

Sources/MySQLKit/MySQLDatabase.swift
Tests/MySQLKitTests/MySQLKitTests.swift
docker-compose.yml

https://github.com/vapor/sql-kit/pull/85

Enum Support

---

Sources/MySQLKit/MySQLDataDecoder.swift
Sources/MySQLKit/MySQLDataEncoder.swift
Sources/MySQLKit/MySQLDatabase.swift

Implement Postgres alter table syntax in `SQLDialect` + add improve coder JSON support.

Alter table syntax + coder fixes

---

.github/workflows/test.yml
Sources/MySQL/Connection/MySQLData.swift
Tests/MySQLTests/MySQLTests.swift

Fixes an issue with sub-second date precision on Linux (#260).

Fix sub-second date precision

---

Tests/MySQLKitTests/MySQLKitTests.swift

Add benchmark run

---

.github/workflows/test.yml
Tests/MySQLKitTests/MySQLKitTests.swift

Also fix tests failing _too_ harshly on connection failure. No release needed.

Make tests respect the LOG_LEVEL env var

---

.github/workflows/test.yml
Sources/MySQLKit/MySQLDatabase.swift
Sources/MySQLKit/MySQLDialect.swift
Tests/LinuxMain.swift
docker-compose.yml

Adds supported SQL trigger options to `MySQLDialect` (#284). 
Also improves CI.

Add dialect trigger options

---

.github/workflows/test.yml
Sources/MySQLKit/MySQLDataDecoder.swift
Sources/MySQLKit/MySQLDataEncoder.swift

Improves encode / decode error messages by including the actual value (#287, fixes #283).

Improve encode/decode error messages

---

Package.swift
README.md
Sources/MySQLKit/ConnectionPool+MySQL.swift
Sources/MySQLKit/MySQLConfiguration.swift
Tests/MySQLKitTests/MySQLKitTests.swift

More information on Vapor 4 official release:
https://forums.swift.org/t/vapor-4-official-release-begins/34802

MySQLKit 4.0.0
